apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bear-host-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: / # We strip the prefix before it passes to our backend or our app wont load as it will get route /bears instead /
spec:
  ingressClassName: nginx
  rules:
  - host: "bear.52.51.164.104.nip.io"
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: bear-svc
            port:
              number: 80
