apiVersion: v1
kind: Service
metadata:
  name: bgb-service
  labels: 
    canary: green-blue
spec:
  selector:
    canary: green-blue
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer
