apiVersion: v1
kind: Pod
metadata:
  name: reddis
  labels:
    app: reddis
spec:
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - mysql
        topologyKey: kubernetes.io/hostname
  containers:
  - name: reddis
    image: supergiantkir/animals:moose
