apiVersion: v1
kind: Pod
metadata:
  name: reddis-pod
  labels:
    app: reddis
spec:
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
            - key: app
              operator: In
              values:
              - mysql
          topologyKey: topology.kubernetes.io/hostname
  containers:
  - name: reddis-pod
    image: supergiantkir/animals:moose
