apiVersion: v1
kind: Pod
metadata:
  name: web-pod
  labels:
    app: reddis
spec:
  affinity:
    podAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: app
              operator: In
              values:
              - reddis
          topologyKey: topology.kubernetes.io/hostname
  containers:
  - name: web-pod
    image: k8s.gcr.io/pause:2.0
